# Generated by Django 4.2.30 on 2026-07-19 17:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('base_servings', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_images/')),
                ('favourite', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('default_unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('item', 'Item'), ('pack', 'Pack'), ('tin', 'Tin'), ('bottle', 'Bottle'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon')], default='item', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('shopping_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shopping.shoppingsection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('item', 'Item'), ('pack', 'Pack'), ('tin', 'Tin'), ('bottle', 'Bottle'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_products', to='shopping.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_products', to='shopping.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(related_name='meals', through='shopping.MealProduct', to='shopping.product'),
        ),
        migrations.AddConstraint(
            model_name='mealproduct',
            constraint=models.UniqueConstraint(fields=('meal', 'product'), name='unique_product_per_meal'),
        ),
    ]
